project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "slides/*.qmd"
    - "helper.qmd"

website:
  page-navigation: true

  title: "Project Oriented Workflows"
  description: "Workshop materials for 1 day workshop"
  site-url: https://www.capro.dev/workshop_rproj/

  repo-url: https://capro-uio.github.io/workshop_rproj/
  repo-actions: [edit, issue]

  navbar:
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/drmowinckels/workshop_rproj
        text: GitHub
    style: docked
    left:
      - text: Slides
        menu:
          - href: slides/00_introduction.html
            text: Introduction
          - href: slides/01_project-oriented.html
            text: Project Oriented Workflows
          - href: slides/02_file-naming.html
            text: File Naming
          - href: slides/03_project-structure.html
            text: Project Structure
          - href: slides/04_package-management.html
            text: Package Management
          - href: slides/educloud_prep.html
            text: EduCloud flavour
      - text: Collaborative docs
        menu:
          - href: https://hackmd.io/@drmowinckels/capro-oslomet-2023/edit
            text: OsloMet 2023
          - href: https://hackmd.io/@drmowinckels/2023-11-21-MPI/edit
            text: MPI - Nov. 2023
          - href: https://hackmd.io/@drmowinckels/dsd_rproj/edit
            text: DS Days UiO - Jan. 2024
    right:
      - href: https://drmowinckels.io
        icon: globe
      - href: https://fosstodon.org/@Drmowinckels
        icon: mastodon

format:
  html:
    theme:
      - default
      - capro_quarto.scss
    toc: true
    code-copy: true
  revealjs:
    height: 900
    width: 1600
    theme:
      - night
      - scss/capro_revealjs.scss
    highlight-style: github-dark
    transition: fade
    chalkboard: true
    slide-number: c/t
    incremental: true
    logo: https://www.capro.dev/images/capro_logo_dark.png

editor: visual

