project:
  type: website

website:
  title: "Project Oriented Workflows"
  navbar:
    left:
      - text: Slides
        menu:
          - href: slides/00_introduction.html
            text: Introduction
          - href: slides/01_project-oriented.html
            text: Project Oriented Workflows
          - href: slides/02_file-naming.html
            text: File Naming
          - href: slides/03_project-structure.html
            text: Project Structure
          - href: slides/04_package-management.html
            text: Package Management
      - text: Collaborative docs
        menu:
          - href: https://hackmd.io/@drmowinckels/capro-oslomet-2023/edit
            text: OsloMet 2023
          - href: https://hackmd.io/@drmowinckels/2023-11-21-MPI/edit
            text: MPI - Nov. 2023


format:
  html:
    theme:
      - default
      - styles.css
    toc: true

editor: visual

